<div class="menu_footer col-sm-7 hidden-xs col-lg-7">
  <?php
  print render($menu_main_footer);
  ?>
</div>
<div class="copyright col-xs-12 col-sm-5 col-lg-5">
  <div class="container_copyright">
    <div class="town_green">
      <a href="http://www.towngreendistrict.com/" target="_blank"><img class="floatRight" src="<?php print base_path() . path_to_theme(); ?>/img/town_green.jpg" alt="Town Green Special Services" height="64px" title="Town Green Special Services" /></a>
    </div>
    <div class="market">
      <a href="/marketnewhaven"><img width="178"  class="floatRight" src="<?php print base_path() . path_to_theme(); ?>/img/market_newhaven.png" alt="Market New Haven" title="Market New Haven" /></a>
    </div>
    <p>&copy; <?php echo date("Y"); ?> INFONewHaven.com&nbsp;&nbsp;|&nbsp;&nbsp;Site by <a target="_blank" href="http://www.thinkcreativegroup.com">think creative group</a></p>
    <p>INFONewHaven.com is a collaborative effort by Market New Haven and Town Green Special Services.</p>
    <p>INFO New Haven Visitor Center: 203-773-9494</p>
    <p><a href="/content/get-listed">Add or request a change to your business listing here!</a></p>
    <p><a href="https://tockify.com/tkf2/submitEvent/a0ff82d14cff11e6b1c3a15367377efa" target="_blank">Click here to list your New Haven event!</a></p>
  </div>
</div>