<div class="content">
  <?php print render(menu_tree_output(menu_tree_all_data("main-menu", NULL, 2))); ?>
  <div class="copyright">
    <div class="town_green">
      <a href="http://www.towngreendistrict.com/" target="_blank"><img class="floatRight" src="<?php print base_path() . path_to_theme(); ?>/img/town_green.jpg" alt="Town Green Special Services" height="64px" title="Town Green Special Services" /></a>
    </div>
    <div class="market">
      <a href="/marketnewhaven"><img class="floatRight" src="<?php print base_path() . path_to_theme(); ?>/img/market_newhaven.png" alt="Market New Haven" title="Market New Haven" /></a>
    </div>
    <p>&copy; 2012 INFONewHaven.com&nbsp;&nbsp;|&nbsp;&nbsp;Site by <a target="_blank" href="http://www.thinkcreativegroup.com">think creative group</a></p>
    <p>INFONewHaven.com is a collaborative effort by Market New Haven</p>
    <p>and Town Green Special Services.</p>
    <p>INFO New Haven Visitor Center: 203-773-9494</p>
    <p><a href="http://infonewhaven.com/content/get-listed" target="_blank">List your New Haven business here!</a></p>
	<p><a href="http://portal.infonewhaven.com/infonewhavencalendar/calendar/" target="_blank">Click here to list your New Haven event!</a></p>
  </div>
</div>